backend:
  name: github
  repo: artsycoder533/netlify-cms

# Specify the path to your custom index.html file
# Note: this assumes that your index.html file is in the admin folder
local_backend:
  url: /admin/index.html

collections:
  - name: "hero"
    label: "Hero"
    files:
      - file: "./dist/data/hero.yml"
        label: "Hero"
        name: "hero"
        fields:
          - { name: "heading", label: "Heading", widget: "string" }
          - { name: "subheading", label: "Subheading", widget: "string" }
          - { name: "background_image", label: "Background Image", widget: "image" }

