backend:
  name: github
  repo: artsycoder533/netlify-cms

collections:
  - name: "hero"
    label: "Hero"
    files:
      - file: "./data/hero.yml"
        label: "Hero"
        name: "hero"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "subtitle", label: "Subtitle", widget: "string" }
          - { name: "background_image", label: "Background Image", widget: "image" }

