backend:
  name: github
  repo: artsycoder533/netlify-cms

collections:
  - name: "hero"
    label: "Hero"
    files:
      - file: "data/hero.yml"
        name: "hero"
        label: "Hero"
        fields:
          - { name: "heading", label: "Heading", widget: "string" }
          - { name: "subheading", label: "Subheading", widget: "string" }
          - { name: "background_image", label: "Background Image", widget: "image" }
